name : Python CI

# Triggers the workflow on any Push or Pull Requests to the main branch or any other brnach that we created

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
# we are speicific jobs that we need to run in the step using ubuntu-latest, becuase it gonna create container and runs the images using ubuntu
jobs:
    test:
        runs-on: ubuntu-latest


        steps:
            # Step 1: Check out the code from repository

            - name: Check out the code
              uses: actions/checkout@v2

            # Step 2: Set up Python environment 
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'

            # Step 3: Install dependencies
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            # Step 4: Run tests
            - name: Run tests
              run: pytest
